# Mediapipe Pose Body Keypoints
mediapipe: {
    Nose: 0,
    LEye_inner: 1,
    LEye: 2,
    LEye_outer: 2,
    REye_inner: 3,
    REye: 4,
    REye_outer: 5,
    LEar: 6,
    REar: 7,
    LMouth: 8,
    RMouth: 9,
    LShoulder: 10,
    RShoulder: 11,
    LElbow: 12,
    RElbow: 13,
    LWrist: 14,
    RWrist: 15,
    LPinky: 16,
    RPinky: 17,
    LIndex: 18,
    RIndex: 19,
    LThumb: 20,
    RThumb: 21,
    LHip: 22,
    RHip: 23,
    LKnee: 24,
    RKnee: 25,
    LAnkle: 26,
    RAnkle: 27,
    LHeel: 28,
    RHeel: 29,
    LBigToe: 30,
    RBigToe: 31,
    Neck: 32
}
# Openpose COCO Body_25 Dataset Keypoints
openpose: {
    Nose: 0,
    Neck: 1,
    RShoulder: 2,
    RElbow: 3,
    RWrist: 4,
    LShoulder: 5,
    LElbow: 6,
    LWrist: 7,
    MidHip: 8,
    RHip: 9,
    RKnee: 10,
    RAnkle: 11,
    LHip: 12,
    LKnee: 13,
    LAnkle: 14,
    REye: 15,
    LEye: 16,
    REar: 17,
    LEar: 18,
    LBigToe: 19,
    LSmallToe: 20,
    LHeel: 21,
    RBigToe: 22,
    RSmallToe: 23,
    RHeel: 24,
    Background: 25
}
